data:
  name: "datarliving"
  data_path: '../data/datarliving'
  batch_size: 160
  tmp_path: "../data/datarliving/glove_tokens"

model:
  name: 'drmm'
  num_classes: 2
  embedding_mapping:
    name: 'base'
    encoders:
      tokens:
        name: 'embedding'
        embedding_dim: 300
        trainable: "False"
        pretrained_file: "../data/glove.840B.300d.txt"
        tmp_dir: "./outputs/drmm_glove_datarlving/embedding"
        namespace: 'tokens'
        dropout_rate: 0.5
      labels:
        name: 'one_hot'
        n_values: 2
        namespace: 'labels'
  optimizer:
    name: 'adagrad'
    learning_rate: 0.03
run_config:
  model_dir: './outputs/drmm_glove_datarlving/'
hparams:
  task: 'rank'
  eval_steps: 316
  early_stopping_max_steps_without_decrease: 200000
  early_stopping_min_steps: 20000



