data:
  name: "quora" # or quora_data_reader
  data_path: '../data/quora'
  train_filename: 'train.tsv'
  valid_filename: 'dev.tsv'
  batch_size: 320
  tmp_path: "../data/quora/glove_new"


model:
  name: 'bilstm'
  num_classes: 2
  hidden_dim: 300
  dropout_rate: 0.5
  embedding_mapping:
    name: 'base'
    encoders:
      tokens:
        name: 'embedding'
        embedding_dim: 300
        trainable: true
        pretrained_file: "../data/glove.840B.300d.txt"
        tmp_dir: "./outputs/embedding"
      labels:
        name: 'one_hot'
        n_values: 2
  optimizer:
    name: 'adam'
    learning_rate: 0.001
    warmup_proportion: 0.1
run_config:
  model_dir: './outputs'
hparams:
  train_steps: 10000
  eval_steps: 100




