data:
  name: "quora" # or quora_data_reader
  data_path: '../data/quora'
  batch_size: 256
  tmp_path: "../data/quora/glove_tokens"

num_classes: 2
export_dir: '../mcan/outputs/mcan_glove_quora/export/best_exporter/1557912245'
output_file: "eval_report.xlsx"