data:
  name: "mnli" # or quora_data_reader
  data_path: '../data/mnli'
  batch_size: 32
  tmp_path: "../data/mnli/glove"

model:
  name: 'esim'
  num_classes: 3
  hidden_dim: 300
  keep_prob: 0.5
  embedding_mapping:
    name: 'base'
    encoders:
      tokens:
        name: 'embedding'
        embedding_dim: 300
        trainable: "False"
        pretrained_file: "../data/glove.840B.300d.txt"
        tmp_dir: "./outputs/esim_glove_mnli/embedding"
        namespace: 'tokens'
        keep_prob: 0.5
      labels:
        name: 'one_hot'
        n_values: 3
        namespace: 'labels'
  optimizer:
    name: 'adam'
    learning_rate: 0.0004
run_config:
  model_dir: './outputs/esim_glove_mnli/'
hparams:
  eval_steps: 306
  early_stopping_max_steps_without_decrease: 1000000
  early_stopping_min_steps: 100000



