data:
  name: "datarliving" # or quora_data_reader
  data_path: '../data/datarliving'
  batch_size: 32
  tmp_path: "../data/datarliving/glove_tokens"

model:
  name: 'bilstm'
  num_classes: 2
  dropout_rate: 0.0
  hidden_dim: 200
  embedding_mapping:
    name: 'base'
    encoders:
      tokens:
        name: 'embedding'
        embedding_dim: 200
        trainable: "False"
        pretrained_file: "../data/datarliving_200.txt"
        tmp_dir: "./outputs/mcan_glove_datarliving/embedding"
        namespace: 'tokens'
        dropout_rate: 0.0
      labels:
        name: 'one_hot'
        n_values: 2
        namespace: 'labels'
  optimizer:
    name: 'adam'
    learning_rate: 0.0003
run_config:
  model_dir: './outputs/mcan_glove_datarliving/'
hparams:
  eval_steps: 80
  early_stopping_max_steps_without_decrease: 200000
  early_stopping_min_steps: 20000



