data:
  name: "datarliving" # or quora_data_reader
  data_path: '../data/datarliving'
  batch_size: 32
  tmp_path: "../data/datarliving/glove_tokens"

model:
  name: 'bilstm'
  num_classes: 3
  keep_prob: 1.0
  hidden_dim: 50
  embedding_mapping:
    name: 'base'
    encoders:
      tokens:
        name: 'embedding'
        embedding_dim: 300
        trainable: "False"
        pretrained_file: "../data/glove.840B.300d.txt"
        tmp_dir: "./outputs/mcan_glove_datarliving/embedding"
        namespace: 'tokens'
        keep_prob: 1.0
      labels:
        name: 'one_hot'
        n_values: 3
        namespace: 'labels'
  optimizer:
    name: 'adam'
    learning_rate: 0.0003
run_config:
  model_dir: './outputs/mcan_glove_datarliving/'
hparams:
  eval_steps: 80
  early_stopping_max_steps_without_decrease: 200000
  early_stopping_min_steps: 20000



