data:
  name: "snli" # or quora_data_reader
  data_path: '../data/snli'
  batch_size: 128
  tmp_path: "../data/snli/glove"
  test_filename: "snli_1.0/snli_1.0_test.jsonl"
  token_indexers:
    tokens:
      name: "single_id"

num_classes: 3
export_dir: '../match_lstm/outputs/match_lstm_glove_snli/export/best_exporter/1556100603'
output_file: "eval_report.xlsx"