data:
  name: "quora" # or quora_data_reader
  data_path: '../data/quora'
  batch_size: 32
  tmp_path: "../data/quora/glove_bimpm"
  token_indexers:
    tokens:
      name: "single_id"
    chars:
      name: "chars"
      max_word_length: 10

num_classes: 2
export_dir: './outputs/bimpm_glove_quora/export/best_exporter/1555442372'
output_file: "eval_report.xlsx"