data:
  name: "mnli"
  data_path: '../data/mnli'
  batch_size: 70
  tmp_path: "../data/mnli/glove_diin"
  max_length: 48
  token_indexers:
    tokens:
      name: "single_id"
    chars:
      name: "chars"
      max_word_length: 16
    pos_tags:
      name: "pos_tags"
    exact_match_labels:
      name: "fields"
      field_name: 'exact_match'
      namespace: 'exact_match_labels'

model:
  name: 'diin'
  num_classes: 3
  hidden_dim: 300
  keep_prob: 0.5
  embedding_mapping:
    name: 'base'
    encoders:
      tokens:
        name: 'embedding'
        embedding_dim: 300
        trainable: "False"
        padding_zero: "True"
        pretrained_file: "../data/glove.840B.300d.txt"
        tmp_dir: "./outputs/esim_diin_glove_mnli/embedding"
        namespace: 'tokens'
      chars:
        name: 'embedding'
        embedding_dim: 8
        trainable: "True"
        padding_zero: "True"
        namespace: 'chars'
      labels:
        name: 'one_hot'
        n_values: 3
        namespace: 'labels'
      pos_tags:
        name: 'one_hot'
        n_values: 47
        namespace: 'pos_tags'

  optimizer:
    name: 'adadelta'
    learning_rate: 0.5

run_config:
  model_dir: './outputs/esim_diin_glove_mnli/'
hparams:
  eval_steps: 150
  early_stopping_max_steps_without_decrease: 1000000
  early_stopping_min_steps: 100000



